server:
  port: 8082

spring:
  application:
    name: risk-engine-service

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/portfolio_db
    username: portfolio_user
    password: portfolio_pass
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true

# Redis Configuration
data:
  redis:
    host: localhost
    port: 6379

# kafka Configuration
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: risk-engine-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Finnhub API Configuration
finnhub:
  api-key: d73hc91r01qjjol32uj0d73hc91r01qjjol32ujg
  base-url: https://finnhub.io/api/v1

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info